### ISSUE TITLE
It is failing at BillingAPI and error msg as  System.ArgumentNullException: Value cannot be null. (Parameter 'json') and     at BillAPI.IdempotentDomainEventHandler.HandleAsync(HandlerEventArgs`1 args) in D:\work\saga-patterns\BillAPI\IdempotentDomainEventHandler.cs:line 38

### ISSUE THREAD

**Issue by tutul2010** [liuzhixin405/outboxpattern#1]
Hi ,

It is failing at BillingAPI and error msg as  System.ArgumentNullException: Value cannot be null. (Parameter 'json')  and below is Calls-stack 
![image](https://github.com/liuzhixin405/outboxpattern/assets/13733464/bd4b062d-5e68-4c61-ba3b-d6ab212d53af)

But , I can see the Msg at rabbitmq as below in Web Page as
![image](https://github.com/liuzhixin405/outboxpattern/assets/13733464/2fc8ce79-142b-4888-a065-16cb191fbc68)

### _Note_: -I am using Docker images of rabbitmq:3-management in Windows 10 -prof -64 bit.

Any things , am i missing or any code change need to do for BillingAPI  side?

Many Thanks for your sweet code..
Tutul

**Comment by liuzhixin405** [comment]
check db,

&nbsp;id is&nbsp;auto-increment









刘志新
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuzhixin405/outboxpattern"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月8日(星期五) 凌晨2:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[liuzhixin405/outboxpattern] It is failing at BillingAPI and error msg as  System.ArgumentNullException: Value cannot be null. (Parameter 'json') and     at BillAPI.IdempotentDomainEventHandler.HandleAsync(HandlerEventArgs`1 args) in D:\work\saga-patterns\BillAPI\IdempotentDomainEventHandler.cs:line 38 (Issue #1)





 
Hi ,
 
It is failing at BillingAPI and error msg as  System.ArgumentNullException: Value cannot be null. (Parameter 'json')  and below is Calls-stack
 image.png (view on web)
 
But , I can see the Msg at rabbitmq as below in Web Page as
 image.png (view on web)
 
Note: -I am using Docker images of rabbitmq:3-management in Windows 10 -prof -64 bit.
 
Any things , am i missing or any code change need to do for BillingAPI  side?
 
Many Thanks for your sweet code..
 Tutul

**Comment by tutul2010** [comment]
Thanks @liuzhixin405 ( 刘志新 ) for response and help.
Use case situation is  as below..

Below is Database tables effects when i ran TradingAPI and BillAPI both

For TradingAPI  running successfully and below are database tables with inserted records  
Order Table -
![image](https://github.com/liuzhixin405/outboxpattern/assets/13733464/0f346884-4ba5-42bc-b861-d21a3116e8dd)

OutBoxes Table -

![image](https://github.com/liuzhixin405/outboxpattern/assets/13733464/0bc5e660-2a44-43a6-804e-db1ab8420bd7)

And rabbitmq -docker ave successfully pushed msg(From TradingAPI) and below is msg in rabbitmq 
![image](https://github.com/liuzhixin405/outboxpattern/assets/13733464/800983eb-e677-43a2-aee9-8d38c985f2b7)

But BillAPI running and have an exception as below
![image](https://github.com/liuzhixin405/outboxpattern/assets/13733464/80cab21c-01da-42c2-9a9e-0ea11d3958bf)

I Could not find any records in BillingRecords and OutboxMessages database table 
![image](https://github.com/liuzhixin405/outboxpattern/assets/13733464/a22b4eca-2ea1-4060-8b87-899df72950a7)

![image](https://github.com/liuzhixin405/outboxpattern/assets/13733464/a8b22442-abf3-4e2b-9dee-f721137cd8aa)

That why  BillAPI was failing because No records were found at BillingRecords and OutboxMessages database table.

Please , suggest that if any things am I missing or any trikes have to do for outbox patterns

Thanks,
Tutul

**Comment by liuzhixin405** [comment]
> Thanks @liuzhixin405 ( 刘志新 ) for response and help. Use case situation is as below..
> 
> Below is Database tables effects when i ran TradingAPI and BillAPI both
> 
> For TradingAPI running successfully and below are database tables with inserted records Order Table - ![image](https://private-user-images.githubusercontent.com/13733464/289266673-0f346884-4ba5-42bc-b861-d21a3116e8dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjM0MDgsIm5iZiI6MTcwMjI2MzEwOCwicGF0aCI6Ii8xMzczMzQ2NC8yODkyNjY2NzMtMGYzNDY4ODQtNGJhNS00MmJjLWI4NjEtZDIxYTMxMTZlOGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyNTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYzVhMDgzYmViZTkyMTQyZDY3YjRjZTAzNDBmMjdiZWFkMjYyOTY4NjQxMWQ2NjZkODFlMzJlNmNkYjdlMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3i0wYxtavMZ-tRka1k_dDYapMEAtmYUvQSlURmznpPU)
> 
> OutBoxes Table -
> 
> ![image](https://private-user-images.githubusercontent.com/13733464/289266775-0bc5e660-2a44-43a6-804e-db1ab8420bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjM0MDgsIm5iZiI6MTcwMjI2MzEwOCwicGF0aCI6Ii8xMzczMzQ2NC8yODkyNjY3NzUtMGJjNWU2NjAtMmE0NC00M2E2LTgwNGUtZGIxYWI4NDIwYmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyNTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZDkyNjUxODAyZjUxNjMyMTAyNzFhNmNlNjUwM2Y1MzdmYjVlYjlmOTY1YzdhNjc5NGRiZWUxNmUwOWEyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QlT611NaCc8VZImCzva9R3s5ir1Ky2kKkyHYQw5BvtY)
> 
> And rabbitmq -docker ave successfully pushed msg(From TradingAPI) and below is msg in rabbitmq ![image](https://private-user-images.githubusercontent.com/13733464/289266933-800983eb-e677-43a2-aee9-8d38c985f2b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjM0MDgsIm5iZiI6MTcwMjI2MzEwOCwicGF0aCI6Ii8xMzczMzQ2NC8yODkyNjY5MzMtODAwOTgzZWItZTY3Ny00M2EyLWFlZTktOGQzOGM5ODVmMmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyNTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3Nzc0ODU2Mzk0YjMwNGZlMjhiMTljZDU4NjU0YWExNDU4NmM5MTc3ZGZiODFhMDYyNzAxYWJmZTA1MmNjM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O_BnOJElZIOlind84xJzFaesKFe-3TskT9960prXKHc)
> 
> But BillAPI running and have an exception as below ![image](https://private-user-images.githubusercontent.com/13733464/289266851-80cab21c-01da-42c2-9a9e-0ea11d3958bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjM0MDgsIm5iZiI6MTcwMjI2MzEwOCwicGF0aCI6Ii8xMzczMzQ2NC8yODkyNjY4NTEtODBjYWIyMWMtMDFkYS00MmMyLTlhOWUtMGVhMTFkMzk1OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyNTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMTdlNjVhODk3ZDZkNjBjZDgwODI0ODZiYzczMzNlZTFmNmVlMzQ2YzBlOTU0OGE1MWU0OWI0NGE0NGMxNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SYaIzIRVqK1A2SpnFLpJrwrtsJBiJuuezlQEXKw-ri0)
> 
> I Could not find any records in BillingRecords and OutboxMessages database table ![image](https://private-user-images.githubusercontent.com/13733464/289267094-a22b4eca-2ea1-4060-8b87-899df72950a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjM0MDgsIm5iZiI6MTcwMjI2MzEwOCwicGF0aCI6Ii8xMzczMzQ2NC8yODkyNjcwOTQtYTIyYjRlY2EtMmVhMS00MDYwLThiODctODk5ZGY3Mjk1MGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyNTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMWI2ZWFjMDdkOWExN2VkODNkYThhYjdmMjIzMTM2NmE5ZmI5NzI3NWNmNDVjNjVmNzQ3NThlMjc5MjEzMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nr4zAWlShOXh5Lak3Z0M_PZIlq7L6Wd239N9RlzcMSo)
> 
> ![image](https://private-user-images.githubusercontent.com/13733464/289267171-a8b22442-abf3-4e2b-9dee-f721137cd8aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjM0MDgsIm5iZiI6MTcwMjI2MzEwOCwicGF0aCI6Ii8xMzczMzQ2NC8yODkyNjcxNzEtYThiMjI0NDItYWJmMy00ZTJiLTlkZWUtZjcyMTEzN2NkOGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyNTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMjFjYjBiOWYwYzlhOTMwMTYzOWEyNjQzNWZkNTc1ODI5OGYzM2U5NDJjNTU1NGZkNjFhYjM5M2M1ZTcyNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5EjG42USVS5ECmLF_GpUSaDFlWgjIYeGh7WLYGsIwCE)
> 
> That why BillAPI was failing because No records were found at BillingRecords and OutboxMessages database table.
> 
> Please , suggest that if any things am I missing or any trikes have to do for outbox patterns
> 
> Thanks, Tutul

in this code  ,your table outboxmessage proceddedonUtc fileds is null， so  ,the back service is not running  or it is have problem, you check must this。 this code is the outboxmessage  pattern core.
![image](https://github.com/liuzhixin405/outboxpattern/assets/30038237/727f5031-ff8f-49ed-9dbd-00ca5e76d744)

**Comment by liuzhixin405** [comment]
completed
